package edu.csc207.fall2024;

/**
 * Constructs an AbstractPerformanceCalculator.
 *
 * @param performance the performance object (must not be null)
 * @param play the play object (must not be null)
 */
public class AbstractPerformanceCalculator {
    protected final Performance performance;
    protected final Play play;

    // Constructor generated by IntelliJ
    public AbstractPerformanceCalculator(Performance performance, Play play) {
        this.performance = performance;
        this.play = play;
    }

    // Factory method
    public static AbstractPerformanceCalculator createPerformanceCalculator(Performance performance, Play play) {
        return new AbstractPerformanceCalculator(performance, play);
    }
}
